# -*- coding: utf-8 -*-
"""NeenOpal - Task 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mQvhEA3HI4LwhsXYdjXpEWRPyHLsM7No

# **Ananya Gupta**

**Dataset Used** : Records Matching Task - data1.csv & 
                 Records Matching Task - data2.csv
 **https://docs.google.com/spreadsheets/d/1g99QKwm2V-_JMXtup7Nk081axpxRYbBx/edit?usp=sharing&ouid=103676608938964511475&rtpof=true&sd=true**
"""

# Importing the required libraries
import numpy as np
import pandas as pd

"""**Reading data1 table from the given dataset to Pandas Dataframe**"""

data1 = pd.read_csv('Records Matching Task - data1.csv')

"""**Combining Order Id + Product ID into one unique column**"""

data1['Unique ID1'] = data1['Order ID'] + " " + data1['Product ID']

# Printing the first 5 rows of data1
data1.head()

"""**It’s imperative to know the count of NaN values for each column before we proceed further.**"""

data1.isnull().sum()

"""**Similarly, for data2 in the given dataset combine the Order ID + Product ID into one column to make a Unique ID for data2**"""

data2 = pd.read_csv('Records Matching Task - data2.csv')

data2['Unique ID2'] = data2['Order ID'] + " " + data2['Product ID']

data2.head()

# check if there exists any null values in data2
data2.isnull().sum()

"""**Combining the 2 datasets into one**"""

combined_data = data1.merge(data2, how = 'outer', left_on = ['Unique ID1'], right_on = ['Unique ID2'])
combined_data.head()

"""***Question-1***
###***How to identify the Records (Order ID + Product ID combination) present in data1 but missing in data2 (Specify the number of records missing in your answer)*** 
"""

# Its similar to finding A-B in sets, we just have to find the difference
ans1 = set(data1['Unique ID1']).difference(set(data2['Unique ID2']))
print(len(ans1))

"""**Or you can create an eniterly new dataframe where records present in data1 are missing in data2**"""

present_in_data1_missing_in_data2 = combined_data[combined_data['Unique ID2'].isna()]
present_in_data1_missing_in_data2.shape[0]

"""***Answer-1***
###***There are total 507 records that are present in data1 but missing in data2.***

***Question-2***
###***How to identify the Records (Order ID + Product ID combination) misisng in data1 but present in data2 (Specify the number of records missing in your answer)***
"""

# Its similar to finding B-A in sets, we just have to find the difference
ans2 = set(data2['Unique ID2']).difference(set(data1['Unique ID1']))
print(len(ans2))

# or you can use method 2
missing_in_data1_present_in_data2 = combined_data[combined_data['Unique ID1'].isna()]
missing_in_data1_present_in_data2.shape[0]

"""***Answer-2***
###***There are total 508 records that are present in data2 but missing in data1.***

***Question-3***
###***Find the Sum of the total Qty of Records missing in data1 but present in data2.***
"""

sum_of_qty_records = missing_in_data1_present_in_data2['Qty_y'].sum()
print(sum_of_qty_records)

"""***Answer-3***
###***The sum of the total Qty of Records missing in data1 but present in data2 are 1956.***

***Question-3***
###***Find the total number of unique records (Order ID + Product ID combination) present in the combined dataset of data1 and data2***
"""

combined_data.shape[0]

"""***Answer-4***
###***The total number of unique records (Order ID + Product ID combination) present in the combined dataset of data1 and data2 are 9986.*** 
"""